services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    tty: true
    stdin_open: true

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - web
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
